### PR TITLE
Fix issue with event list

### LINKED ISSUE #48: Switching back to "Today" from "Week view" does not update list
Switching back to Day View from Week View does not work. The list does not get updated to only contain today's events.

I created 3 events. 2 for today and 1 for tomorrow.
When I am on "Today" I see 2 events for today. 
Then I switch to "Week view" and I see 3 events for the week, 2 for today and 1 for tomorrow.
Then I switch back to "Today" and I still see 3 events, 2 for today and 1 for tomorrow.

Switching from "Week view" to "Day view" and then to "Today" works fine.

### PR DESCRIPTION
**Pull request by malbx**
Fixes #48: The event list does not display current events in certain cases.  This happens when switching between the "Today", "Day", and "Week" event list view.  These changes address that issue by:
1) Properly setting the mode before switching to the day view
2) Preventing the date from inadvertently being modified by calls to `SQLiteManager::GetEventsOfWeek`

### CODE REVIEW

File: src/DayView.cpp [hunk 1]
```diff
@@ -61,6 +61,10 @@ DayView::SetDate(const BDate& date)
 	fDate = date;
 }
 
+void DayView::SetMode(int32 mode) {
```
Comment (pulkomandy) [inline src/DayView.cpp:64]: newline before {

Comment (malbx) [reply src/DayView.cpp]: Thanks for catching that.

**Comment by malbx** [comment]
Hi @pulkomandy.  I have addressed the style issue that you identified.  Are there any other changes that need to be made?
